### PR TITLE
#5 Split Incentives for studies into two new fields

### PR DESCRIPTION
**Pull request by xavier630**
Solves issue #5. Splits the incentive field of a study into incentive type and incentive detail.
This involves changing the front end when creating, editing and displaying studies, as well as changing what the server and the database expect.

To be honest, I think that it's larger than a small issue as it took many hours and the database side of it got very technical.

### CODE REVIEW

**Comment by xavier630** [comment]
@softeng-701 - could you please review/merge these changes. Thank you!

**Comment by softeng-701** [comment]
@xavier630 Please stash your commits, thanks!

**Comment by xavier630** [comment]
@softeng-701 With regards to squashing, I constantly merged master in between my commits to ensure that I stayed up to date with Kelly's master, resolving conflicts as I merged it. As such I get all of the commits from master when trying to squash my commits which makes it undesirable to squash the whole branch. Can we please merge it without squashing so that I don't squash in the commits from master?

This issue has come up numerous times in Visual Git as well: 

eg here's a similar issue from Visual Git:
```
I resolved merge conflicts but was unable to squash it as the all the commits on Kelly's master appeared when attempting to squash so was told by Kelly not to squash.

```

Here's what happens when I go to squash my 6 or so commits ( I have all of the commits from master). 

image

image

**Comment by kblincoe** [comment]
You should be able to squash non-sequential commits: https://www.intertech.com/Blog/git-how-to-combine-non-consecutive-multiple-commits-into-one/

If you have trouble, you can skip squashing on this one, but squash on all future pull requests.

**Comment by softeng-701** [comment]
@xavier630 I am merging this one now! Make sure to squash in the future.

**Comment by xavier630** [comment]
Thanks! I'll do my best.

**Comment by xavier630** [comment]
@softeng-701 Do you also agree that this one has a medium worth of content? (See my first comment). It is similar in depth to this medium here: https://github.com/kblincoe/QualOpt_SE701/pull/80

Cheers,
Xavier

**Comment by TheGuardianWolf** [comment]
@softeng-701 @xavier630 

Commit 2c6b39b removes the 'incentives' property on study, a test depended on this and haven't been updated.

StudyResourceIntTest.java

I am fixing this on my branch, please review this change below.

https://github.com/kblincoe/QualOpt_SE701/pull/108/commits/cf2ac08a0d52a55bc9f8d9bd90bec6c61e27bdf1

**Comment by TheGuardianWolf** [comment]
The new schema that was merged in is also invalid, the old one I updated to remove a clob declaration on one of the new properties that should be a varchar instead.

https://github.com/TheGuardianWolf/QualOpt_SE701/blob/3f7c0ca1e298365e5155db6a98fcc9ad1a308b03/src/main/resources/config/liquibase/changelog/20170806142424_added_entity_Study.xml

**Comment by TheGuardianWolf** [comment]
The liquibase configuration is also failing because of clob/blob problems, I'm not sure how to resolve this, could I get some help?

```
Schema-validation: wrong column type encountered in column [incentive_type] in table [study]; found [clob (Types#CLOB)], but expecting [blob (Types#BLOB)]
```

When I change it to blob, it says expecting CLOB...

**Comment by xavier630** [comment]
@TheGuardianWolf Did you have any luck? Is this due to the new Spring Version?

**Comment by xavier630** [comment]
@TheGuardianWolf Also I've reviewed the new test and it looks good 👍

**Comment by xavier630** [comment]
Yep just gave it a go. Interesting how the build fails - I was able to build/run it fine when I opened the PR.

**Comment by TheGuardianWolf** [comment]
If I had to guess it's the squashing, I had issues performing my squash which reverted many changes.

**Comment by TheGuardianWolf** [comment]
I'm planning to shove my pull in today, it's been delayed long enough since each time it comes to merge my changes, several pulls are merged before mine and conflict...

**Comment by xavier630** [comment]
👍 Also - which command did you build it with to get the liquibase error? I'm not able to reproduce it right now on master but I'll keep trying. Were you on master or your own branch?

**Comment by TheGuardianWolf** [comment]
```mvnw clean test```

**Comment by softeng-701** [comment]
Okay Kelly @kblincoe 
@TheGuardianWolf @xavier630 Guys, Please let me know when done!

**Comment by TheGuardianWolf** [comment]
@kblincoe I was meaning to talk to you today about how I can get my pull request merged, each time another pull request gets merged in, I have to adjust the new code to work for SB 2. After that I have to wait a bit for authors to review the changes.

What I was thinking was either merge mine in as the last pull that's done, and give me some time to patch up everyone's code when all the pulls are in, or put mine in after master is fixed this time so people can use the new API.

@softeng-701 The fixes are on another PR #141 rather than this, that one should be priority so I can test my upgrade branch.

**Comment by xavier630** [comment]
@softeng-701 Still waiting for one teammate to review it. As @TheGuardianWolf  said, the fixes are on #141

**Comment by softeng-701** [comment]
@xavier630 @TheGuardianWolf #141 merged.. will do this merge after another team member reviews.

**Pull request merged**
