### PR TITLE
Link Service to Send Invitation button; now sends out emails

### PR DESCRIPTION
**Pull request by wilmol**
Solution to #71 
- Created a new REST endpoint POST /api/studies/send in StudyResource using new StudyService object
- Created a new method StudyService#sendInvitationEmail(Study) 
- Linked POST endpoint to Send Invitation button via study-detail.component#sendInvitation() and study.service#send().

Currently using a test gmail account (tt7199425@gmail.com) as I don't know how to authenticate the users email (possibly related to #37). However, it is successfully sending invitations from this gmail account.

Test:
1. Login as admin (admin:admin).
2. Create participants and a study.
3. View the study and click Send Invitation.
4. Participants now receive invitation emails.

### CODE REVIEW

**Comment by pulkitkalra** [comment]
Firewall for some antiviruses (E.g. avast) was blocking the email from being sent.
@wilmol This should fix it:
`props.put("mail.smtp.ssl.trust", "smtp.gmail.com");`
In the `StudyService`, method: `getUserEmailSession()`

**Comment by softeng-701** [comment]
@wilmol Please resolve the conflicts asap, thank you.

**Comment by wilmol** [comment]
@softeng-701 fixed :)

**Comment by softeng-701** [comment]
@wilmol Awesome!

**Comment by AprajitGandhi** [comment]
Tested it, good unit tests - they all pass too. Good commenting. Approved

**Pull request merged**
