### PR TITLE
Created an about page, hid studies and participants and changed the footer text.

### PR DESCRIPTION
**Pull request by sidpartha1**
- Created routing for the about page and included it in the navbar routing.
- Added message recognizing original creators and contributors in the about page
- At the moment about component and home component almost look identical, but the home component is to be redesigned according to #30 

-Advise if any new materials are to be added to the about page

### CODE REVIEW

**Comment by sidpartha1** [comment]
Also updated footer to show University of Auckland as opposed to  by Dinal and Fraser

**Comment by sidpartha1** [comment]
Completed issues #13 , #18 and #29

**Comment by softeng-701** [comment]
@sidpartha1 I am closing #13 #18 #29

**Comment by umih874** [comment]
The code looks well structured and modular. All the changes are working properly. I have reviewed these changes before they were approved by the softeng-701 team but I forgot to approve it. I added these changes to my repo so I can work on Issue #30 and I tested them before I started working on my issue but I forgot to approve these changes on here.

**Pull request merged**
