### PR TITLE
Improved participant selection when creating a study

### PR DESCRIPTION
**Pull request by xavier630**
Solves issue number #38, to improve the process of selecting participants when creating a study. This can be found here:
https://github.com/kblincoe/QualOpt_SE701/issues/38

I addressed this issue in several ways:
* The selection box is much larger and will scale with the number of participants.
* You no longer have to highlight selections blue to select them, or ctrl/shift click to select multiple.
* Every participant now has a checkbox next to them to make an easy and clear selection.
* I've added select/deselect all buttons for ease of use when selecting participants.

### CODE REVIEW

**Comment by xavier630** [comment]
@softeng-701 - Could you please review/merge the changes?

**Comment by softeng-701** [comment]
@xavier630 Please stash your commits, thanks!

**Comment by softeng-701** [comment]
@xavier630 resolve conflicts, please!

**Comment by xavier630** [comment]
Working on it now. :)

**Comment by xavier630** [comment]
@softeng-701 Hi, the branch is all squashed and there are no conflicts with master. Thanks for all of your hard work managing this repo.

Cheers,
Xavier

**Comment by softeng-701** [comment]
@xavier630 Will do it, once the previous PRs are merged!

**Comment by xavier630** [comment]
@softeng-701 Thanks!

**Comment by softeng-701** [comment]
@xavier630 why do we have conflict again? can you please check, thanks!

**Comment by xavier630** [comment]
@softeng-701 Yep, I'll resolve it now.

**Comment by xavier630** [comment]
@softeng-701 All resolved.

**Pull request merged**
